all: main main2 main3 main4
main: main.cpp
	g++ -o main main.cpp -lncurses
main2: main2.cpp
	g++ -o main2 main2.cpp -lncurses
main3: main3.cpp
	g++ -o main3 main3.cpp -lncurses
main4: ./main4创建窗口.cpp
	g++ -o main4 ./main4创建窗口.cpp -lncurses
main5: main5颜色系统.cpp
	g++ -o main5 main5颜色系统.cpp -lncurses
clean:
	rm main main2 main3 main4 main5
