all: main copy mt copy2
main: main.cpp
	g++ -g -o main main.cpp
copy: copy.cpp
	g++ -g -o copy copy.cpp
mt: maketest.cpp
	g++ -g -o mt maketest.cpp
copy2: copy2.cpp
	g++ -g -o copy2 copy2.cpp
clean:
	rm main copy mt copy2
