all: main ps segment ok
main: main.cpp
	g++ -g -o main main.cpp 
ps: ps.cpp
	g++ -g -o ps ps.cpp
segment: segment.cpp
	g++ -g -o segment segment.cpp
ok: ok.cpp
	g++ -g -o ok ok.cpp
clean: 
	rm main ps segment ok

