all: main
main: main.cpp
	g++ -g -o main main.cpp 
copy: copy.cpp
	g++ -g -o copy copy.cpp
mt: mt.cpp
	g++ -g -o mt mt.cpp
down_nyahentai: down_nyahentai.cpp
	g++ -g -o down_nyahentai down_nyahentai.cpp -lcurl
clean: 
	rm main copy mt down_nyahentai

